services:
  hwzthatcore:
    build:
      context: .
      dockerfile: 7.4/Dockerfile
    container_name: php-hwzthatcore
    environment:
      VIRTUALHOST_NAMES: "core.hwzthat.local,lms.hwzthat.local,client1.hwzthat.local"
    volumes:
      - ../pazhassi_howzthat-watw/source:/var/www/core.hwzthat.local/source
      - ../pazhassi_howzthat-watw/source:/var/www/client1.hwzthat.local/source
      - ../pazhassi_edbix_lms/source:/var/www/lms.hwzthat.local/source/public
      - ../:/var/www/html
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mysql

  hwzthat_booking:
    build:
      context: .
      dockerfile: 8.3/Dockerfile
    container_name: php-83
    environment:
      VIRTUALHOST_NAMES: "booking.hwzthat.local"
    volumes:
      - ../rayssports_facility_booking:/var/www/booking.hwzthat.local
      - ../:/var/www/html
    ports:
      - "82:80"
    restart: always
    depends_on:
      - mysql
  club7ms_portal:
    build:
      context: .
      dockerfile: 8.1/Dockerfile
    container_name: php-81
    environment:
      VIRTUALHOST_NAMES: "club7ms_portal.local"
    volumes:
      - ../club7ms_portal:/var/www/club7ms_portal.local
      - ../:/var/www/html
    ports:
      - "86:80"
    restart: always
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.40
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "9306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    ports:
      - 9091:80
    volumes:
      - /sessions
    links:
      - mysql

volumes:
  db_data:
    driver: local
